apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-bitcoin-microservice
  labels:
    app: aws-bitcoin-microservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aws-bitcoin-microservice
  template:
    metadata:
      labels:
        app: aws-bitcoin-microservice
    spec:
     {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "aws-bitcoin-microservice.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: aws-bitcoin-microservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .valueFrom }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
              {{- else }}
              value: {{ .value }}
              {{- end }}
            {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}

